carts/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', cart, name='cart'),
    path('add_cart/<int:product_id>/', add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', remove_cart_item, name='remove_cart_item'),
    path('checkout/', checkout, name='checkout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf.urls.static import static
from config import settings

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('sadmin/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    # Orders
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .views import *

urlpatterns = [
  path('', store, name='store'),
  path('category/<slug:category_slug>/', store, name='products_by_category'),
  path('category/<slug:category_slug>/<slug:product_slug>/', product_detail, name='product_detail'),
  path('search/', search, name='search'),
  path('submit_review/<int:product_id>', submit_review, name='submit_review'),
]

store/models.py
from django.db import models
from category.models import Category
from django.urls import reverse
from accounts.models import User
from django.db.models import Avg, Count


class Product(models.Model):
    product_name = models.CharField(max_length=255, unique=True, verbose_name='Producto')
    slug = models.SlugField(max_length=255, unique=True, verbose_name='Slug')
    description = models.TextField(max_length=500, blank=True, verbose_name='Descripción')
    old_price = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True, verbose_name='Precio anterior')
    price = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='Precio')
    images = models.ImageField(upload_to='photos/products', verbose_name='Galería')
    stock = models.IntegerField(blank=True, null=True, verbose_name='Cantidad en mano')
    is_available = models.BooleanField(default=True, verbose_name='Disponible')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Categoría')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Actualizado')

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'

    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.slug])

    def averageReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg

    def countReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count

    def __str__(self):
        return self.product_name


class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)

    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True)


variation_category_choice = (
    ('color', 'Color'),
    ('size', 'Talla'),
)


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Producto')
    variation_category = models.CharField(max_length=100, choices=variation_category_choice, verbose_name='Tipo de variación')
    variation_value = models.CharField(max_length=100, verbose_name='Variación')
    is_active = models.BooleanField(default=True, verbose_name='Activo')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Fecha')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Actualizado')

    class Meta:
        verbose_name = 'Variación'
        verbose_name_plural = 'Variaciones'

    objects = VariationManager()

    def __str__(self):
        return self.variation_value


class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Producto')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Usuario')
    subject = models.CharField(max_length=100, verbose_name='Asunto')
    review = models.TextField(max_length=500, verbose_name='Reseña')
    rating = models.FloatField(verbose_name='Calificación')
    ip = models.CharField(max_length=20, blank=True, verbose_name='Dirección IP')
    status = models.BooleanField(default=True, verbose_name='Estado')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Fecha')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Actualización')

    class Meta:
        verbose_name = 'Reseña'
        verbose_name_plural = 'Reseñas'

    def __str__(self):
        return self.subject


class ProductGallery(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE, verbose_name='Producto')
    image = models.ImageField(upload_to='store/products', verbose_name='Imagen')

    class Meta:
        verbose_name = 'Imagen'
        verbose_name_plural = 'Imágenes'

    def __str__(self):
        return self.product.product_name

store/forms.py
from django.forms import ModelForm, TextInput
from store.models import ReviewRating


class ReviewRatingForm(ModelForm):
    
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']
        widgets = {
            'subject': TextInput(
                attrs={
                    'class': 'form-control',
                }
            )
        }

store/views.py
from django.shortcuts import render, get_object_or_404, redirect
from accounts.models import UserProfile
from carts.models import CartItem
from orders.models import OrderProduct
from .models import Product, ProductGallery, ReviewRating
from category.models import Category
from carts.views import _cart_id
# from django.http import HttpResponse
from django.core.paginator import Paginator
from django.db.models import Q
from store.forms import ReviewRatingForm
from django.contrib import messages


def store(request, category_slug=None):
    categories = None
    products = None

    if category_slug != None:
        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(
            category=categories, is_available=True)
        paginator = Paginator(products, 6)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()
    else:
        products = Product.objects.all().filter(is_available=True).order_by('id')
        paginator = Paginator(products, 6)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()

    context = {
        'products': paged_products,
        'product_count': product_count,
    }

    return render(request, 'store/store.html', context)


def product_detail(request, category_slug, product_slug):
    try:
        single_product = Product.objects.get(category__slug=category_slug, slug=product_slug)
        in_cart = CartItem.objects.filter(cart__cart_id=_cart_id(request), product=single_product).exists()
    except Exception as e:
        raise e

    if request.user.is_authenticated:
        try:
            orderproduct = OrderProduct.objects.filter(user=request.user, product_id=single_product.id).exists()
        except OrderProduct.DoesNotExist:
            orderproduct = None
    else:
        orderproduct = None

    # Get the reviews
    reviews = ReviewRating.objects.filter(product_id=single_product.id, status=True)

    # Get the product gallery
    product_gallery = ProductGallery.objects.filter(product_id=single_product.id)

    context = {
        'single_product': single_product,
        'in_cart': in_cart,
        'orderproduct': orderproduct,
        'reviews': reviews,
        'product_gallery': product_gallery,
    }

    return render(request, 'store/product_detail.html', context)


def search(request):
    products = None
    paged_products = None
    product_count = None
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            products = Product.objects.order_by(
                '-created_at').filter(Q(product_name__icontains=keyword) | Q(description__icontains=keyword))
            if 'keyword' in request.GET and request.GET['keyword']:
                page = request.GET.get('page')
                keyword = request.GET['keyword']
                paginator = Paginator(products, 3)
            paged_products = paginator.get_page(page)
            product_count = products.count()

    context = {
        'products': paged_products,
        'product_count': product_count,
        'keyword': keyword,
    }
    return render(request, 'store/store.html', context)


def submit_review(request, product_id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        try:
            reviews = ReviewRating.objects.get(user__id=request.user.id, product__id=product_id)
            form = ReviewRatingForm(request.POST, instance=reviews)
            form.save()
            messages.success(request, '¡Gracias! Tu reseña ha sido actualizada.')
            return redirect(url)
        except ReviewRating.DoesNotExist:
            form = ReviewRatingForm(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.subject = form.cleaned_data['subject']
                data.rating = form.cleaned_data['rating']
                data.review = form.cleaned_data['review']
                data.ip = request.META.get('REMOTE_ADDR')
                data.product_id = product_id
                data.user_id = request.user.id
                data.save()
                messages.success(request, '¡Gracias! Tu reseña ha sido enviada.')
                return redirect(url)

store/templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- ============================ COMPONENT 2 ================================= -->
<section class="section-content padding-y bg">
    <div class="container">
        <div class="card">
            <div class="row no-gutters">
                <aside class="col-sm-6 border-right">
                    <article class="gallery-wrap">
                        <div class="img-big-wrap mainImagen text-center">
                            <img src="{{ single_product.images.url }}">
                        </div>
                        <!-- img-big-wrap.// -->
                        <div class="thumbs-wrap">
                            <a href="{{ single_product.images.url }}" class="item-thumb featureImagen"><img src="{{ single_product.images.url }}"></a>
                            {% for i in product_gallery %}
                            <a href="{{ i.image.url }}" class="item-thumb featureImagen"><img src="{{ i.image.url }}"></a>
                            {% endfor %}
                        </div>
                        <!-- thumbs-wrap.// -->
                    </article>
                    <!-- gallery-wrap .end// -->
                </aside>
                <main class="col-sm-6">
                    <form action="{% url 'add_cart' single_product.id %}" method="POST">
                        {% csrf_token %}
                        <article class="content-body">
                            <a href="#" class="text-primary btn-link">Ropa</a>
                            <h3 class="title">{{ single_product.product_name }}</h3>
                            <div class="rating-star">
                                <span>
                                    <i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o{% elif single_product.averageReview >= 0.5 and single_product.averageReview < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
                                    <i class="fa fa-star{% if single_product.averageReview < 1.5 %}-o{% elif single_product.averageReview >= 1.5 and single_product.averageReview < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
                                    <i class="fa fa-star{% if single_product.averageReview < 2.5 %}-o{% elif single_product.averageReview >= 2.5 and single_product.averageReview < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
                                    <i class="fa fa-star{% if single_product.averageReview < 3.5 %}-o{% elif single_product.averageReview >= 3.5 and single_product.averageReview < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
                                    <i class="fa fa-star{% if single_product.averageReview < 4.5 %}-o{% elif single_product.averageReview >= 4.5 and single_product.averageReview < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
                                    <span class="mr-3">{{ single_product.countReview }} reseñas</span>
                                    <a href="#" class="btn-link mr-3 text-muted">
                                        <i class="fa fa-heart" aria-hidden="true"></i> Enviar a favorito
                                    </a>
                                    <a href="#" class="btn-link text-muted">
                                        <i class="fas fa-book-open"></i> Comparar
                                    </a>
                                </span>
                            </div>
                            <hr />
                            <p>{{ single_product.description }}</p>
                            <div class="item-option-select">
                                <div class="form-group">
                                    <label for="color">
                                        <strong>Color</strong>
                                    </label>
                                    <select class="form-control" name="color" id="color" required>
                                        <option value="" disabled selected>
                                            Seleccionar color
                                        </option>
                                        {% for i in single_product.variation_set.colors %}
                                        <option value="{{ i.variation_value | lower }}">
                                            {{ i.variation_value | capfirst }}
                                        </option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="item-option-select">
                                <div class="form-group">
                                    <label for="size">
                                        <strong>Talla</strong>
                                    </label>
                                    <select class="form-control" name="size" id="size" required>
                                        <option value="" disabled selected>
                                            Seleccionar talla
                                        </option>
                                        {% for i in single_product.variation_set.sizes %}
                                        <option value="{{ i.variation_value | lower }}">
                                            {{ i.variation_value | capfirst }}
                                        </option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="h3 mb-3">
                                <var class="price h4">${{ single_product.price }}</var>
                            </div>
                            <!-- price-wrap.// -->
                            <div class="form-row">
                            {% if single_product.stock <= 0 %}
                                <div class="col-12">
                                    <div class="alert alert-danger" role="alert">
                                        <p>Producto agotado</p>
                                    </div>
                                </div>
                            {% else %}
                                <button type="submit" class="btn btn-primary">
                                    Añadir al carrito <i class="fas fa-shopping-cart"></i>
                                </button>
                            {% endif %}
                            </div>
                            <!-- row.// -->
                        </article>
                        <!-- product-info-aside .// -->
                    </form>
                </main>
                <!-- col.// -->
            </div>
            <!-- row.// -->
        </div>
        <!-- card.// -->
        <br />
        <div class="row">
            <div class="col-md-9">
                <header class="section-heading">
                    <h3>Escribe tu reseña</h3>
                </header>
                <form action="{% url 'submit_review' single_product.id %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="">¿Cómo calificarías este producto?</label>
                        <br>
                        <div class="rate">
                            <input type="radio" name="rating" value="5" id="rating10" required><label for="rating10" title="5"></label>
                            <input type="radio" name="rating" value="4.5" id="rating9" required><label for="rating9" title="4.5" class="half"></label>
                            <input type="radio" name="rating" value="4" id="rating8" required><label for="rating8" title="4"></label>
                            <input type="radio" name="rating" value="3.5" id="rating7" required><label for="rating7" title="3.5" class="half"></label>
                            <input type="radio" name="rating" value="3" id="rating6" required><label for="rating6" title="3"></label>
                            <input type="radio" name="rating" value="2.5" id="rating5" required><label for="rating5" title="2.5" class="half"></label>
                            <input type="radio" name="rating" value="2" id="rating4" required><label for="rating4" title="2"></label>
                            <input type="radio" name="rating" value="1.5" id="rating3" required><label for="rating3" title="1.5" class="half"></label>
                            <input type="radio" name="rating" value="1" id="rating2" required><label for="rating2" title="1"></label>
                            <input type="radio" name="rating" value="0.5" id="rating1" required><label for="rating1" title="0.5" class="half"></label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="subject">Asunto:</label>
                        <input type="text" class="form-control" name="subject" id="subject" required>
                    </div>
                    <div class="form-group">
                        <label for="review">Comentario:</label>
                        <textarea class="form-control" name="review" id="review" rows="3" required></textarea>
                    </div>
                    {% if user.is_authenticated %}
                        {% if orderproduct %}
                        <button type="submit" class="btn btn-primary mb-3">Enviar reseña</button>
                        {% else %}
                        <p class="mb-3">Debes comprar este producto para escribir una reseña.</p>
                        {% endif %}
                    {% else %}
                    <p class="mb-3">Para escribir una reseña debes iniciar sesión <span><a href="{% url 'login' %}">Inicia sesión</a></span></p>
                    {% endif %}
                    {% include 'includes/alerts.html' %}
                </form>
                <header class="section-heading">
                    <h4>Reseñas de clientes</h4>
                    <div class="rating-star mb-3">
                        <span>
                            <i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o{% elif single_product.averageReview >= 0.5 and single_product.averageReview < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if single_product.averageReview < 1.5 %}-o{% elif single_product.averageReview >= 1.5 and single_product.averageReview < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if single_product.averageReview < 2.5 %}-o{% elif single_product.averageReview >= 2.5 and single_product.averageReview < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if single_product.averageReview < 3.5 %}-o{% elif single_product.averageReview >= 3.5 and single_product.averageReview < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if single_product.averageReview < 4.5 %}-o{% elif single_product.averageReview >= 4.5 and single_product.averageReview < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
                            <span>{{single_product.countReview}} reseñas</span>
                        </span>
                    </div>
                </header>
                {% for review in reviews %}
				<article class="box mb-3">
					<div class="icontext w-100">
                        <img src="{{ userprofile.profile_picture.url }}" class="img-xs icon rounded-circle" alt="Imagen de perfil de {{ review.user.full_name }}">
                        <div class="text">
                            <span class="date text-muted float-md-right">{{ review.updated_at }}</span>
                            <h6 class="mb-1">{{ review.user.full_name }}</h6>
                            <div class="rating-star">
								<span>
									<i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o {% endif %}" aria-hidden="true"></i>
									<i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
									<i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o {% endif %}" aria-hidden="true"></i>
									<i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o {% endif %}" aria-hidden="true"></i>
									<i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o {% endif %}" aria-hidden="true"></i>
								</span>
							</div>
                        </div>
					</div> <!-- icontext.// -->
					<div class="mt-3">
						<h6>{{review.subject}}</h6>
						<p>
							{{review.review}}
						</p>
					</div>
				</article>
                {% endfor %}
            </div>
            <!-- col.// -->
        </div>
        <!-- row.// -->
    </div>
</section>
{% endblock content %}

{% block javascript %}
    <script>
        $(document).ready(function () {
            $('.thumbs-wrap a').click(function (e) {
                e.preventDefault();
                $('.mainImagen img').attr('src', $(this).attr('href'));
            });
        });
    </script>
{% endblock %}